### ISSUE TITLE
error when pushing docker image : no credentials found

### ISSUE THREAD

**Issue by palver7** [Kenza-AI/sagify#120]
The problem:
I try to push a docker image to ECR using sagify push following the steps in https://kenza-ai.github.io/sagify/ 
but I got this error message :
Error when retrieving credentials from Ec2InstanceMetadata: No credentials found in credential_source referenced in profile :aws:iam::...:role/SagemakerSagify
Traceback (most recent call last):
  File "/media/daniel/Data/linuxprogs/miniconda3/envs/sagify/bin/sagify", line 8, in <module>
    sys.exit(cli())
  File "/media/daniel/Data/linuxprogs/miniconda3/envs/sagify/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/media/daniel/Data/linuxprogs/miniconda3/envs/sagify/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/media/daniel/Data/linuxprogs/miniconda3/envs/sagify/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/media/daniel/Data/linuxprogs/miniconda3/envs/sagify/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/media/daniel/Data/linuxprogs/miniconda3/envs/sagify/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/media/daniel/Data/linuxprogs/miniconda3/envs/sagify/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/media/daniel/Data/linuxprogs/miniconda3/envs/sagify/lib/python3.7/site-packages/sagify/commands/push.py", line 58, in push
    image_name=image_name)
  File "/media/daniel/Data/linuxprogs/miniconda3/envs/sagify/lib/python3.7/site-packages/sagify/api/push.py", line 37, in push
    image_name])
  File "/media/daniel/Data/linuxprogs/miniconda3/envs/sagify/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/media/daniel/Data/linuxprogs/miniconda3/envs/sagify/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['src/sagify_base/push.sh', 'latest', 'ap-southeast-1', '', 'default', '', 'sagify-demo']' returned non-zero exit status 255.

Additional Context:
In the select IAM user step, I choose the only user available, the admin user created according to the aws guide. 
In the credentials and config files the profile name is [default]. I added the role_arn according to the sagify guide and source_profile = default in the aws config file

if I run sagify push it seems sagify created a new profile with the name of the arn role I created. 

I need help to resolve this error.

**Comment by ilazakis** [comment]
Hi @palver7, thanks for raising this.

Just to verify, are you running this on your local machine?

**Comment by palver7** [comment]
@ilazakis yes I am running this on my laptop.
